"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { FilePlus, FolderOpen, Home, Search, Settings, Share2, Star, Trash2, X } from "lucide-react";
import { useEffect, useState, type ReactNode } from "react";
import { Logo } from "@/features/marketing";
import { ThemeToggle } from "@/components/theme-toggle";
import { routes } from "@/lib/constants";

const items = [[Home, "Home", "/dashboard"], [FolderOpen, "My files", "/documents"], [FilePlus, "Recent", "/recent"], [Star, "Starred", "/starred"], [Share2, "Shared with me", "/shared"]] as const;
const commands = [{ label: "Go to home", href: "/dashboard" }, { label: "Browse my files", href: "/documents" }, { label: "Create a new document", href: "/documents/new" }, { label: "Open settings", href: "/settings" }];

export function AppShell({ children }: { children: ReactNode }) {
  const path = usePathname(); const router = useRouter(); const [collapsed, setCollapsed] = useState(false); const [paletteOpen, setPaletteOpen] = useState(false); const [query, setQuery] = useState("");
  useEffect(() => { function onKeyDown(event: KeyboardEvent) { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setPaletteOpen(true); } if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "b") { event.preventDefault(); setCollapsed((value) => !value); } if (event.key === "Escape") setPaletteOpen(false); } window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown); }, []);
  const pageName = path.split("/").filter(Boolean).map((segment) => `${segment.charAt(0).toUpperCase()}${segment.slice(1)}`).join(" / ") || "Home";
  const visibleCommands = commands.filter((command) => command.label.toLowerCase().includes(query.toLowerCase()));
  function runCommand(href: string) { setPaletteOpen(false); setQuery(""); router.push(href); }
  return <div className={`app-shell ${collapsed ? "sidebar-collapsed" : ""}`}><aside className="sidebar"><Logo /><Link className="btn new-file" style={{ marginTop: 22 }} href={routes.newDocument}><FilePlus size={16} /> <span>New file</span></Link><nav className="sidebar-nav" aria-label="Workspace navigation">{items.map(([Icon, label, href]) => <Link title={label} className={`nav-item ${path === href ? "active" : ""}`} href={href} key={href}><Icon size={18} /><span>{label}</span></Link>)}<br /><Link title="Trash" className={`nav-item ${path === "/trash" ? "active" : ""}`} href="/trash"><Trash2 size={18} /><span>Trash</span></Link><Link title="Settings" className={`nav-item ${path === "/settings" ? "active" : ""}`} href="/settings"><Settings size={18} /><span>Settings</span></Link></nav><div className="sidebar-footer"><div className="user-chip"><span className="avatar">AM</span><div><b>Alex Morgan</b><small className="muted" style={{ display: "block" }}>alex@docly.dev</small></div></div></div></aside><section className="app-main"><header className="app-header"><span className="muted">{pageName}</span><div style={{ display: "flex", alignItems: "center", gap: 8 }}><button className="header-search" type="button" onClick={() => setPaletteOpen(true)} aria-label="Search and navigate"><Search size={15} />Search documents <kbd>⌘ K</kbd></button><ThemeToggle /><span className="avatar">AM</span></div></header>{children}<Link className="fab" href={routes.newDocument} aria-label="Create a new file"><FilePlus size={22} /></Link></section>{paletteOpen && <div className="command-backdrop" role="presentation" onMouseDown={() => setPaletteOpen(false)}><section className="command-menu" role="dialog" aria-modal="true" aria-label="Command menu" onMouseDown={(event) => event.stopPropagation()}><div className="command-input"><Search size={17} /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search commands…" aria-label="Search commands" /><button className="icon-button" type="button" onClick={() => setPaletteOpen(false)} aria-label="Close command menu"><X size={17} /></button></div><div className="command-results">{visibleCommands.length ? visibleCommands.map((command) => <button key={command.href} type="button" onClick={() => runCommand(command.href)}>{command.label}</button>) : <p className="muted">No matching commands</p>}</div></section></div>}</div>;
}
