import Link from "next/link";
import { Eye, EyeOff } from "lucide-react";
import { Logo } from "@/features/marketing";
import { routes } from "@/lib/constants";

export function AuthPage({ mode }: { mode: "login" | "register" }) {
  const login = mode === "login";
  return <div className="auth-page"><main className="auth-form-pane"><div className="auth-card"><Logo /><h1>{login ? "Welcome back" : "Create your account"}</h1><p>{login ? "Pick up where your team left off." : "Start building better shared context today."}</p><div>{!login && <div className="form-group"><label>Name</label><input className="input" autoComplete="name" /></div>}<div className="form-group"><label>Email</label><input className="input" type="email" autoComplete="email" /></div><div className="form-group"><div className="form-row"><label>Password</label>{login && <a className="muted" href="#">Forgot password?</a>}</div><div className="password-wrap"><input className="input" type="password" autoComplete="current-password" /><button className="icon-button" type="button" aria-label="Show password"><Eye size={16} /></button></div>{!login && <><div className="strength"><i /><i /><i /><i /></div><small className="muted">Use 8+ characters with a number or symbol</small></>}</div><label className="muted"><input type="checkbox" /> {login ? "Remember me" : "I agree to the Terms and Privacy Policy"}</label><button className="btn full" type="button">{login ? "Log in" : "Create account"}</button></div><div className="divider">or continue with</div><div className="socials"><button className="btn secondary" type="button">Google</button><button className="btn secondary" type="button">GitHub</button></div><p className="muted" style={{ textAlign: "center", marginTop: 22 }}>{login ? "Don't have an account? " : "Already have an account? "}<Link style={{ color: "var(--primary)" }} href={login ? routes.register : routes.login}>{login ? "Sign up" : "Log in"}</Link></p></div></main><aside className="brand-panel"><Logo /><blockquote>“Nexora gives our ideas one clear place to grow — without getting in the way.”</blockquote><p>Built for teams who care about clarity.</p></aside></div>;
}
