"use client";

import Link from "next/link";
import { ArrowLeft, Bold, Check, Code2, FileText, Italic, Link2, List, ListOrdered, Loader2, MoreHorizontal, Redo2, Share2, Undo2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { routes } from "@/lib/constants";
import type { DocumentSummary } from "@/types/document";

type Tool = "bold" | "italic" | "bulletList" | "orderedList" | "code" | "link";
const toolLabels: Record<Tool, string> = { bold: "Bold", italic: "Italic", bulletList: "Bulleted list", orderedList: "Numbered list", code: "Code block", link: "Add link" };

export function Editor({ document }: { document: DocumentSummary | null }) {
  const [title, setTitle] = useState(document?.title ?? "Untitled document"); const [saving, setSaving] = useState(false); const [active, setActive] = useState<Tool[]>([]); const [shared, setShared] = useState(false); const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => () => { if (timer.current) clearTimeout(timer.current); }, []);
  function markDirty() { setSaving(true); if (timer.current) clearTimeout(timer.current); timer.current = setTimeout(() => setSaving(false), 700); }
  function toggle(tool: Tool) { setActive((current) => current.includes(tool) ? current.filter((item) => item !== tool) : [...current, tool]); markDirty(); }
  const ToolButton = ({ tool, Icon }: { tool: Tool; Icon: typeof Bold }) => <button type="button" className={`tool ${active.includes(tool) ? "active" : ""}`} onClick={() => toggle(tool)} aria-label={toolLabels[tool]} aria-pressed={active.includes(tool)} title={toolLabels[tool]}><Icon size={16} /></button>;
  return <main className="editor"><header className="editor-top"><Link className="icon-button" href={routes.dashboard} aria-label="Back to dashboard"><ArrowLeft size={18} /></Link><FileText size={16} className="muted" /><input className="editor-title" aria-label="Document title" value={title} onChange={(event) => { setTitle(event.target.value); markDirty(); }} /><span className="sync" aria-live="polite">{saving ? <Loader2 className="spin" size={15} /> : <Check size={15} />}<span>{saving ? "Saving…" : "Saved"}</span></span><span className="collabs" aria-label="Maya Chen and Noah Williams are viewing"><span className="avatar">MC</span><span className="avatar">NW</span></span><button type="button" className="btn" onClick={() => setShared(true)}><Share2 size={16} />Share</button><button className="icon-button" type="button" aria-label="More document options"><MoreHorizontal size={18} /></button></header><nav className="editor-toolbar" aria-label="Editor toolbar"><button className="tool" type="button" aria-label="Undo" title="Undo"><Undo2 size={16} /></button><button className="tool" type="button" aria-label="Redo" title="Redo"><Redo2 size={16} /></button><i className="tool-sep" /><ToolButton tool="bold" Icon={Bold} /><ToolButton tool="italic" Icon={Italic} /><i className="tool-sep" /><ToolButton tool="bulletList" Icon={List} /><ToolButton tool="orderedList" Icon={ListOrdered} /><ToolButton tool="code" Icon={Code2} /><ToolButton tool="link" Icon={Link2} /></nav>{shared && <div className="share-banner" role="status"><span>Anyone in your workspace with the link can view this document.</span><button className="icon-button" type="button" aria-label="Close sharing notice" onClick={() => setShared(false)}>×</button></div>}<section className="editor-desk"><article className="paper doc-prose"><h1>{title || "Untitled document"}</h1>{document ? <><p>This is a focused space for the details that move work forward. The editor surface is deliberately UI-first, ready to be replaced by a rich-text engine without changing the surrounding chrome.</p><h2>What we&apos;re solving</h2><p>We need a shared view of priorities, decisions, and the people responsible for the next step. Keep this document useful by making the important things easy to find.</p><blockquote>Good collaboration makes the next decision clearer, not louder.</blockquote><h2>Next steps</h2><ul><li>Confirm the scope with the project team.</li><li>Capture feedback directly in the document.</li><li>Turn the decision into a small, owned action.</li></ul><pre>status: ready for review</pre></> : <p className="muted">Start writing…</p>}</article></section></main>;
}
